# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 03:00
from __future__ import unicode_literals

from django.db import migrations, models
import gridgraph.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('image', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=gridgraph.models.upload_location, width_field='width_field')),
                ('width_field', models.IntegerField(default=0)),
                ('height_field', models.IntegerField(default=0)),
                ('publish', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
