# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 21:44
from __future__ import unicode_literals

from django.db import migrations, models
import gridgraph.models


class Migration(migrations.Migration):

    dependencies = [
        ('gridgraph', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graph',
            name='height_field',
        ),
        migrations.RemoveField(
            model_name='graph',
            name='width_field',
        ),
        migrations.AlterField(
            model_name='graph',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=gridgraph.models.upload_location),
        ),
    ]
