# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gridgraph', '0002_auto_20160629_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='graph',
            name='csv_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
