# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 08:17
from __future__ import unicode_literals

from django.db import migrations, models
import gridgraph.models


class Migration(migrations.Migration):

    dependencies = [
        ('gridgraph', '0003_graph_csv_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='graph',
            options={'ordering': ['-publish']},
        ),
        migrations.AddField(
            model_name='graph',
            name='name',
            field=models.CharField(default='graph', max_length=120),
        ),
        migrations.AlterField(
            model_name='graph',
            name='csv_file',
            field=models.FileField(blank=True, null=True, upload_to=gridgraph.models.upload_location),
        ),
    ]
