# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gridgraph', '0004_auto_20160630_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graph',
            name='title',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
